trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'KmipCards/Client'
      api_location: 'KmipCards/Api'
      output_location: '/src'
      azure_static_web_apps_api_token: $(deployment_token)